spring.application.name=config-server
server.port=8888

# Configuration du dépôt Git centralisé
spring.cloud.config.server.git.uri=https://github.com/BabacarNdaoKgl/cloud-config-repo-enda.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.timeout=10

# Désactiver l'authentification de base pour simplifier
spring.cloud.config.server.git.skip-ssl-validation=false